package-lock.json, package.json, src/components/choiceSignUpType/ChoiceSignUpType.tsx, src/components/choiceSignUpType/SignUpType.tsx, src/components/common/footer/Footer.tsx, src/components/common/header/Header.tsx, src/components/common/header/headerLeft/HeaderLeftContainer.tsx, src/components/common/header/headerLeft/Menu.tsx, src/components/common/header/headerRight/AfterLogin.tsx, src/components/common/header/headerRight/BeforeLogin.tsx, src/components/common/header/headerRight/HeaderRightContainer.tsx, src/components/common/spinner/Spinner.tsx, src/components/login/Login.tsx, src/components/login/LoginForm.tsx, src/components/login/SocialLogin.tsx, src/components/signUp/SignUp.tsx, src/components/signUp/SignUpForm.tsx, src/pages/ChoiceSignUpTypePage.tsx, src/pages/LoginPage.tsx, src/pages/SignUpPage.tsx, tailwind.config.js
- page routing 추가
- suspense 코드 추가
- spinner 라이브러리 추가
- tailwind css color 코드 수정 및 지정한 변수로 클래스명 수정
=> page routing 추가, suspense 코드 추가, spinner 라이브러리 추가

src/Router.tsx, src/components/mentorDetail/MentorDetailContainer.tsx, src/components/mentorDetail/MentorInfo.tsx, src/components/mentorDetail/MentorIntroduce.tsx, src/components/mentorDetail/mentorReivew/MentorReviewContainer.tsx, src/components/mentorDetail/mentorReivew/MentorReviewItems.tsx, src/components/mentorDetail/mentorReivew/MentorReviewList.tsx, src/components/mentorDetail/mentorReivew/NonExistsReview.tsx, src/components/mentorDetail/pastMentoring/NonExistsPastMentoring.tsx, src/components/mentorDetail/pastMentoring/PastMentoringContainer.tsx, src/components/mentorDetail/pastMentoring/PastMentoringItem.tsx, src/components/mentorDetail/pastMentoring/PastMentoringList.tsx, src/input.css, src/pages/MentorDetailPage.tsx
- 멘토 상세 페이지 UI 생성
- 멘토 상세 페이지 라우트 추가
- 멘토 상세 페이지 진행했던 멘토링 제목 ellipsis css 추가
=> PR : feature/mentorDetailPageUI

src/components/choiceSignUpType/ChoiceSignUpTypeContainer.tsx, src/components/login/LoginContainer.tsx, src/components/mentor/mentoringList/MentorItem.tsx, src/components/mentoring/MentoringContainer.tsx, src/components/mentoring/mentoringList/MentoringItem.tsx, src/components/signUp/SignUpContainer.tsx, src/pages/ChoiceSignUpTypePage.tsx, src/pages/LoginPage.tsx, src/pages/MentoringPage.tsx, src/pages/SignUpPage.tsx
- item hover 시 scale 설정
- 파일명 변경
=> PR : Feature/itemhoverscale

src/components/main/thirdsection/MentorCard.tsx
=> PR : fix/noUse

package.json, vercel.json
- build 시 tailwind css 생성 명령어 추가
- build 시 tailwind css 생성 명령어 추가
-  vercel.json 추가
=> PR : feature/distribution

vercel.json
=> PR : fix/build

src/components/main/Main.tsx, src/pages/MainPage.tsx
- 메인 페이지의 헤더부분에 홈 버튼을 누르면 화면이 안보이는 현상 해결
- Main.tsx의 헤더,푸터 부분 MainPage.tsx파일로 옮김
=> 🐛 fix : 메인 페이지 Suspense추가

vite.config.ts
=> PR : feature/proxy

src/components/main/fifthsection/DeadlineMentoringList.tsx, src/components/main/thirdsection/MentorCardList.tsx
=> 🎨 improve : 메인페이지 코드 수정

package-lock.json, package.json, src/Router.tsx, src/components/common/spinner/Loading.tsx, src/utils/alert.ts
- develop branch merge error 해결
- develop branch merge error 해결
=> PR : fix/develop

.gitignore, src/components/login/KaKaoCallback.tsx, src/components/login/NaverCallback.tsx, src/components/login/SocialLogin.tsx
- 최초 소셜로그인 시 회원가입 페이지로 이동 되게 수정
- gitignore env 파일 추가
=> PR : Feature/socialSignUp

src/Router.tsx, src/components/login/LoginForm.tsx, src/components/mentorRegistration/registrationStep/ThirdStep.tsx, src/components/mentoring/mentoringList/MentoringList.tsx, src/components/mentoringDetail/MentoringDetailContainer.tsx, src/components/mentoringDetail/mentoringInfoWithApply/MentoringContent.tsx, src/components/mentoringDetail/mentoringInfoWithApply/MentoringInfo.tsx, src/components/mentoringDetail/mentoringInfoWithApply/MentoringInfoWithApply.tsx, src/components/mentoringEdit/MentoringEditContainer.tsx, src/components/mentoringEdit/MentoringTitle.tsx, src/components/mentoringEdit/SaveAndBackButton.tsx, src/components/mentoringEdit/essentialInfo/EsseentialPrice.tsx, src/components/mentoringEdit/essentialInfo/EssentialCategory.tsx, src/components/mentoringEdit/essentialInfo/EssentialHeadCount.tsx, src/components/mentoringEdit/essentialInfo/EssentialInfoContainer.tsx, src/components/mentoringEdit/essentialInfo/EssentialMentoringPeriod.tsx, src/data/mentoringEditForm.ts, src/hooks/useAxios.ts, src/interface/mentoringDetailInfo.ts, src/interface/mentoringInfo.ts, src/main.tsx, src/pages/MentoringEditPage.tsx
- 멘토링 편집 페이지 UI 추가
- 멘토링 상세조회 기능 추가
- 멘토링 상세조회 route params 변경
- mentoringDetail interface 생성
- 멘토링 상세조회, 삭제, 수정 기능 추가
- 멘토링 수정 시 전역 form 생성
- route suspense true 추가
- API 호출 useAxios로 수정
- react-quill css 선언 위치 수정
- 데이터 조회 후 set
- interface mentoring, mentoring props 추가
- 멘토링 수정 페이지 추가
- 멘토링 수정 페이지 route 추가
- API 호출 시 공통으로 사용할 useAxios 추가
=> PR : Feature/mentoringDetailEditDelete

src/components/community/CommnunityContainer.tsx, src/components/mentoringRegistration/MentoringRegistrationContainer.tsx, src/components/mentoringRegistration/MentoringTitle.tsx, src/components/mentoringRegistration/SaveAndBackButton.tsx, src/components/mentoringRegistration/essentialInfo/EsseentialPrice.tsx, src/components/mentoringRegistration/essentialInfo/EssentialHeadCount.tsx, src/components/mentoringRegistration/essentialInfo/EssentialInfoContainer.tsx, src/components/mentoringRegistration/essentialInfo/EssentialMentoringPeriod.tsx, src/data/mentoringRegistrationData.ts
- 멘토링 등록 테스트 코드 추가
- 불필요 코드 삭제
- 멘토링 등록 기능을 위한 전역 form 데이터 atom 생성
- 멘토링 등록api 호출까지 완료
=> PR : Feature/mentoringRegistration

src/Router.tsx, src/components/mentor/MentorContainer.tsx, src/components/mentor/mentoringList/MentorItem.tsx, src/components/mentor/mentoringList/MentorList.tsx, src/components/mentorDetail/MentorDetailContainer.tsx, src/components/mentorDetail/MentorInfo.tsx, src/components/mentorDetail/MentorIntroduce.tsx, src/interface/mentorItem.ts
- 멘토 목록 조회, 멘토 상세 조회 기능 추가
- 멘토 목록 조회, 멘토 상세 조회 기능 추가
=> PR : feature/mentor

index.html, package-lock.json, package.json, postcss.config.cjs, postcss.config.js, src/main.tsx, tailwind.config.js
=> PR : feature/tailwind

src/components/mentoringDetail/MentorProfile.tsx, src/interface/mentoringInfo.ts
- 멘토 프로필 이미지 추가
- API 수정으로 인한 코드 수정
- 멘토링 상세조회시 멘토 이미지 추가
=> PR : feature/mentorinDetailProfileImg

src/components/mentoringRoom/Calendar.tsx, src/components/mentoringRoom/ScheduleAddButton.tsx, src/components/mentoringRoom/ScheduleAddModal.tsx
=> ♻️ refactor: code refactor

src/Router.tsx, src/components/common/header/headerRight/AfterLogin.tsx, src/components/communityDetail/CommunitySideBar.tsx, src/state/notification.ts
- emitter 삭제 기능 추가
- emitterId 전역 상태 추가
- 페이지 닫거나 로그아웃 시 삭제 기능 실행
=> PR : feature/deleteEmitter

src/components/common/pagination/Pagination.tsx, src/components/common/search/Sort.tsx, src/components/common/searchType/SearchType.tsx, src/components/community/CommunityContainer.tsx, src/components/community/LocationWithCreate.tsx, src/components/community/communityList/CommunityItem.tsx, src/components/community/communityList/CommunityList.tsx, src/components/community/communitySearch/SearchCriteriaWithKeyword.tsx, src/components/communityDetail/comment/CommentContainer.tsx, src/components/communityDetail/comment/CommentList.tsx, src/components/communityDetail/comment/CommentSubmit.tsx, src/components/mentor/MentorContainer.tsx, src/components/mentoring/MentoringContainer.tsx, src/hooks/useUrl.ts, src/interface/comment.ts, src/main.tsx, src/pages/CommunityPage.tsx
- 커뮤니티 댓글 페이징 기능 추가
- 페이지네이션 컴포넌트 공통 컴포넌트로 분리
- useUrl 코드 수정
=> PR : Feature/commintyQuery

src/Router.tsx, src/components/mentoring/mentoringList/MentoringList.tsx, src/components/mentoringDetail/MentoringDetailContainer.tsx, src/components/mentoringDetail/mentoringInfoWithApply/Button.tsx, src/components/mentoringDetail/mentoringInfoWithApply/MentoringInfoWithApply.tsx, src/components/mentoringpayment/PaymentConfirmation.tsx, src/pages/PaymentPage.tsx
=> PR: feature/paymentAPI

src/Router.tsx, src/components/common/chatAndScrollTop/chat/Chat1On1.tsx, src/components/common/chatAndScrollTop/chat/ChatBtn.tsx, src/components/common/chatAndScrollTop/chat/chatList/ExistsChatList.tsx, src/components/mentoringDetail/mentoringInfoWithApply/Button.tsx, src/components/mentoringDetail/mentoringInfoWithApply/MentoringInfo.tsx, src/components/mentoringRoom/Calendar.tsx, src/components/mentoringRoom/groupChat/GroupChatBtn.tsx, src/components/mentoringRoom/groupChat/GroupChatContainer.tsx, src/data/chatHistory.ts, src/data/groupChatHistory.ts, src/pages/CommunityPage.tsx, src/pages/MentoringRoomPage.tsx, src/pages/MyPage.tsx, src/pages/PaymentPage.tsx, src/pages/PaymentSuccessPage.tsx, src/state/chatState.ts
=> PR : Feature/groupChat

src/components/mentoringpayment/PaymentConfirmation.tsx, tsconfig.json
=> PR : feature/buildError

src/components/mentoringDetail/mentoringInfoWithApply/Button.tsx
Reverts MentoMate/mentomate-FE#102
=> Revert "PR : Feature/errorHandling"

tailwind.config.js
=> PR : revert

src/components/main/Main.tsx, src/components/main/MentoringCard.tsx, src/components/main/mainFifthSection/DeadlineMentoringList.tsx, src/components/main/mainFifthSection/FifthSection.tsx, src/components/main/mainFirstSection/FirstSection.tsx, src/components/main/mainFirstSection/MentoringCardList.tsx, src/components/main/mainFourthSection/CommunityItem.tsx, src/components/main/mainFourthSection/CommunityItemList.tsx, src/components/main/mainFourthSection/FourthSection.tsx, src/components/main/mainSecondSection/SecondSection.tsx, src/components/main/mainSixSection/AllMentoringDataList.tsx, src/components/main/mainSixSection/SixSection.tsx, src/components/main/mainThirdSection/ThirdSection.tsx, src/components/main/mainThirdSection/ThirdSectionMentorItem.tsx, src/components/main/mainThirdSection/ThirdSectionMentorList.tsx, src/components/mentor/mentorList/MentorItem.tsx, src/components/mentorDetail/MentorInfo.tsx, src/components/mentorDetail/mentorReview/NonExistsReview.tsx, src/components/mentorDetail/pastMentoring/NonExistsPastMentoring.tsx, src/components/mentorDetail/pastMentoring/PastMentoringList.tsx, src/components/mentoring/mentoringList/MentoringItem.tsx, src/hooks/useUrl.ts, src/interface/mentorItem.ts, vercel.json
- useUrl 수정 및 css 수정
- 멘토링 상세조회 css 수정
=> PR : Feature/mainPage

src/components/mentoringRoom/Calendar.tsx, src/components/mentoringRoom/DayCellContent.tsx, src/components/mentoringRoom/MentoringEndButton.tsx, src/components/mentoringRoom/MentoringInfoModal.tsx, src/components/mentoringRoom/ScheduleReadModal.tsx, src/state/mentorState.ts
- 멘토 여부에 따라 기능 제한(멘토링 종료, 일정 추가,수정,삭제)
- 현재 날짜보다 초과한 멘토링 다음달로 안넘어 가는 버그 수정
- 멘토 여부에 따라 기능 제한(멘토링 종료, 일정 추가,수정,삭제)
- 현재 날짜보다 초과한 멘토링 다음달로 안넘어 가는 버그 수정
=> PR: fix/mentoringRoomFix 
